"""cheater init: first-run wizard + write .cheater/AGENTS.md."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from cheater.config import (
    CheaterConfig,
    first_run_wizard,
    load_config,
    project_config_path,
    save_config,
    user_config_path,
)


AGENTS_MD_TEMPLATE = """\
# Cheater Project Memory

Cheater reads this file for project-specific hints. Generated by `cheater init`.

## Project type
- language: {language}
- test command: {test_cmd}
- lint command: {lint_cmd}
- entry points: {entry_points}

## Repository map
- (cheater will fill this in as you explore)

## Notes
- (project-specific cheater notes go here)
"""


def _detect_language(root: Path) -> str:
    if (root / "pyproject.toml").is_file() or (root / "setup.py").is_file():
        return "python"
    if (root / "package.json").is_file():
        return "javascript/typescript"
    if (root / "Cargo.toml").is_file():
        return "rust"
    if (root / "go.mod").is_file():
        return "go"
    if (root / "pom.xml").is_file() or (root / "build.gradle").is_file():
        return "java"
    return "unknown"


def _detect_test_cmd(root: Path) -> str:
    if (root / "pyproject.toml").is_file():
        return "pytest"
    if (root / "package.json").is_file():
        return "npm test"
    if (root / "Cargo.toml").is_file():
        return "cargo test"
    if (root / "go.mod").is_file():
        return "go test ./..."
    if (root / "pom.xml").is_file():
        return "mvn test"
    return "echo 'no test command detected'"


def _detect_lint_cmd(root: Path) -> str:
    if (root / "pyproject.toml").is_file():
        return "ruff check ."
    if (root / "package.json").is_file():
        return "npx eslint ."
    if (root / "Cargo.toml").is_file():
        return "cargo clippy"
    return "echo 'no lint command detected'"


def _detect_entry_points(root: Path) -> str:
    candidates: list[str] = []
    for name in ("main.py", "app.py", "index.js", "index.ts", "main.go", "main.rs", "src/main.rs"):
        if (root / name).is_file():
            candidates.append(name)
    return ", ".join(candidates) if candidates else "(none detected)"


def run(args: argparse.Namespace) -> int:
    root = Path(args.repo) if args.repo else Path.cwd()
    cfg = load_config(root)
    cfg.project_root = str(root.resolve())

    if args.noninteractive:
        first_run_wizard(cfg, noninteractive=True)
    else:
        # If stdin is not a tty, fall back to non-interactive
        import sys
        if not sys.stdin.isatty():
            first_run_wizard(cfg, noninteractive=True)
        else:
            first_run_wizard(cfg, noninteractive=False)

    # Save project config
    proj_dir = root / ".cheater"
    proj_dir.mkdir(parents=True, exist_ok=True)
    proj_path = proj_dir / "config.toml"
    save_config(cfg, proj_path)
    sys.stdout.write(f"\nWrote project config: {proj_path}\n")

    # Also save user config so the user has a global default
    user_path = user_config_path()
    user_cfg = load_config()
    user_cfg.first_run_done = True
    save_config(user_cfg, user_path)
    sys.stdout.write(f"Wrote user config: {user_path}\n")

    # Write .cheater/AGENTS.md
    agents_md = proj_dir / "AGENTS.md"
    if not agents_md.exists() or args.force:
        agents_md.write_text(
            AGENTS_MD_TEMPLATE.format(
                language=_detect_language(root),
                test_cmd=_detect_test_cmd(root),
                lint_cmd=_detect_lint_cmd(root),
                entry_points=_detect_entry_points(root),
            ),
            encoding="utf-8",
        )
        sys.stdout.write(f"Wrote project memory: {agents_md}\n")

    sys.stdout.write("\n=== cheater init done ===\n")
    sys.stdout.write("Next steps:\n")
    sys.stdout.write("  - Run `cheater doctor` to check setup.\n")
    sys.stdout.write("  - Run `cheater` to open the TUI.\n")
    sys.stdout.write("  - Run `cheater ask \"...\"` headless.\n")
    return 0
